name: Pack
on:
  push:
    branches: [ main ]
jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-rc.1.21463.6
    - name: Pack
      run: dotnet pack -warnaserror -c Release
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: NuGet packages
        path: artifacts/pack/*.nupkg